In [1]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [3]:
iris = datasets.load_iris(as_frame = True).frame
iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [5]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [7]:
iris.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [8]:
iris.head(2)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0

In [10]:
# Splitting the preprocessed iris dataset into X and y
X = iris.drop("target",axis=1)
y = iris["target"]
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [12]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)
X_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3

In [15]:
# For Support Vector Classifier - Scale the input data
# For Support Vector Regressor - Scale both input and output data 

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svc = SVC()
svc.fit(X_train_scaled, y_train)

y_pred = svc.predict(X_test_scaled)

In [17]:
from sklearn.metrics import accuracy_score, classification_report, f1_score
print("Accuracy : ",accuracy_score(y_test, y_pred))
print("classification_report : ",classification_report(y_test, y_pred))

Accuracy :  0.9333333333333333
classification_report :                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [18]:
# Linear Kernel
svc = SVC(kernel="linear")
svc.fit(X_train_scaled, y_train)

y_pred = svc.predict(X_test_scaled)
print("Accuracy : ",accuracy_score(y_test, y_pred))

Accuracy :  0.9111111111111111

In [19]:
# Polynomial Kernel
svc = SVC(kernel="poly")
svc.fit(X_train_scaled, y_train)

y_pred = svc.predict(X_test_scaled)
print("Accuracy : ",accuracy_score(y_test, y_pred))

Accuracy :  0.8666666666666667

In [20]:
# Sigmoid Kernel
svc = SVC(kernel="sigmoid")
svc.fit(X_train_scaled, y_train)

y_pred = svc.predict(X_test_scaled)
print("Accuracy : ",accuracy_score(y_test, y_pred))

Accuracy :  0.9111111111111111

In [21]:
# Hyper Parameter Turning
C_vals = [0.5, 1, 2, 3, 4, 5, 6]

for c_val in C_vals:
    svc = SVC(kernel="rbf", C=c_val)
    svc.fit(X_train_scaled, y_train)
    
    y_pred = svc.predict(X_test_scaled)
    print("C = ",c_val,"& Accuracy : ",accuracy_score(y_test, y_pred))

C =  0.5 & Accuracy :  0.9111111111111111
C =  1 & Accuracy :  0.9333333333333333
C =  2 & Accuracy :  0.9111111111111111
C =  3 & Accuracy :  0.9111111111111111
C =  4 & Accuracy :  0.9333333333333333
C =  5 & Accuracy :  0.9333333333333333
C =  6 & Accuracy :  0.9333333333333333